
import { useState } from "react";
import { Upload, Camera, Wand2, Check, DollarSign, Package } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { toast } from "sonner";

const SellerDashboard = () => {
  const [uploadedImages, setUploadedImages] = useState<string[]>([]);
  const [aiGenerating, setAiGenerating] = useState(false);
  const [listingGenerated, setListingGenerated] = useState(false);

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files) {
      const newImages = Array.from(files).map(file => URL.createObjectURL(file));
      setUploadedImages(prev => [...prev, ...newImages]);
      
      // Simulate AI processing
      setTimeout(() => {
        setAiGenerating(true);
        toast.success("Images uploaded! AI is analyzing your product...");
        
        setTimeout(() => {
          setAiGenerating(false);
          setListingGenerated(true);
          toast.success("Perfect listing generated by AI!");
        }, 3000);
      }, 1000);
    }
  };

  const mockListing = {
    title: "Vintage Nike Air Jordan 1 High OG 'Chicago' - Size 10",
    description: "Authentic 1985 Nike Air Jordan 1 in the iconic Chicago colorway. Shows minimal wear with original box and all accessories. This classic basketball shoe features premium leather construction and the timeless red, white, and black color scheme that made it legendary.",
    condition: "Excellent (8.5/10)",
    suggestedPrice: "$1,200",
    category: "Sneakers & Athletic Shoes",
    estimatedValue: "$1,000 - $1,400"
  };

  return (
    <div className="grid lg:grid-cols-2 gap-8">
      {/* Upload Section */}
      <Card className="border-0 shadow-lg bg-white/80 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Camera className="w-5 h-5 text-blue-600" />
            Upload Product Photos
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-blue-400 transition-colors">
            <input
              type="file"
              multiple
              accept="image/*"
              onChange={handleImageUpload}
              className="hidden"
              id="image-upload"
            />
            <label htmlFor="image-upload" className="cursor-pointer">
              <Upload className="w-12 h-12 text-gray-400 mx-auto mb-4" />
              <p className="text-lg font-medium text-gray-600 mb-2">
                Drop your product photos here
              </p>
              <p className="text-sm text-gray-500">
                AI will analyze and create the perfect listing
              </p>
            </label>
          </div>

          {uploadedImages.length > 0 && (
            <div>
              <p className="font-medium text-gray-700 mb-2">Uploaded Images:</p>
              <div className="grid grid-cols-3 gap-2">
                {uploadedImages.map((image, index) => (
                  <img
                    key={index}
                    src={image}
                    alt={`Product ${index + 1}`}
                    className="w-full h-20 object-cover rounded-lg border"
                  />
                ))}
              </div>
            </div>
          )}

          {aiGenerating && (
            <div className="bg-blue-50 p-4 rounded-lg">
              <div className="flex items-center gap-2 mb-2">
                <Wand2 className="w-4 h-4 text-blue-600 animate-spin" />
                <span className="font-medium text-blue-800">AI Analyzing Product...</span>
              </div>
              <Progress value={75} className="h-2" />
              <p className="text-sm text-blue-600 mt-2">
                Identifying product details, condition, and market value...
              </p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Generated Listing */}
      <Card className="border-0 shadow-lg bg-white/80 backdrop-blur-sm">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Wand2 className="w-5 h-5 text-purple-600" />
            AI-Generated Listing
            {listingGenerated && (
              <Badge className="bg-green-100 text-green-700 border-green-200">
                <Check className="w-3 h-3 mr-1" />
                Ready
              </Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {!listingGenerated ? (
            <div className="text-center py-8 text-gray-500">
              <Package className="w-12 h-12 mx-auto mb-4 opacity-50" />
              <p>Upload product photos to see AI magic!</p>
            </div>
          ) : (
            <>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Title</label>
                <input
                  type="text"
                  value={mockListing.title}
                  className="w-full p-3 border border-gray-300 rounded-lg bg-white"
                  readOnly
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                <textarea
                  value={mockListing.description}
                  rows={4}
                  className="w-full p-3 border border-gray-300 rounded-lg bg-white resize-none"
                  readOnly
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Condition</label>
                  <input
                    type="text"
                    value={mockListing.condition}
                    className="w-full p-3 border border-gray-300 rounded-lg bg-white"
                    readOnly
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">AI Suggested Price</label>
                  <div className="flex items-center p-3 border border-gray-300 rounded-lg bg-green-50">
                    <DollarSign className="w-4 h-4 text-green-600 mr-1" />
                    <span className="font-semibold text-green-700">{mockListing.suggestedPrice}</span>
                  </div>
                </div>
              </div>

              <div className="bg-gray-50 p-4 rounded-lg">
                <p className="text-sm text-gray-600 mb-2">
                  <strong>Market Analysis:</strong> {mockListing.estimatedValue}
                </p>
                <p className="text-sm text-gray-600">
                  <strong>Category:</strong> {mockListing.category}
                </p>
              </div>

              <Button className="w-full bg-gradient-to-r from-green-600 to-blue-600 hover:from-green-700 hover:to-blue-700">
                <Check className="w-4 h-4 mr-2" />
                Publish Listing with One Click
              </Button>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default SellerDashboard;
